using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Fluxer.Net;

/// <remarks>
/// <see href="https://github.com/fluxerapp/fluxer/blob/848269a4d4df7349acfc861ff926b17fe4c4a548/packages/schema/src/domains/message/EmbedSchemas.tsx#L111"/>
/// </remarks>
public class MessageEmbedJson : MessageEmbedChildJson
{
    /// <summary>
    /// Internal nested embeds generated by unfurlers
    /// </summary>
    [JsonProperty("children")]
    [MaxLength(1)]
    public MessageEmbedChildJson[]? Children { get; set; }
}
