<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>annotations</Nullable>
    <DebugSymbols>true</DebugSymbols>
    <EmbedAllSources>true</EmbedAllSources>
    <DebugType>portable</DebugType>
	
	<!-- NuGet package info -->
    <PackageId>Fluxer.Net</PackageId>
    <Version>1.0.0</Version>
    <Authors>Nexfinity</Authors>
    <Company>Nexfinity</Company>
    <Description>A .NET library for Fluxer bot development.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/nexfinity/fluxer.net</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Nexfinity/Fluxer.Net.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

    <!-- Optional but good practice -->
    <PackageTags>fluxer;bot;library;dotnet</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Livekit.Server.Sdk.Dotnet" Version="1.0.13" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="serilog" Version="3.0.1" />
    <PackageReference Include="serilog.sinks.console" Version="4.1.0" />
    <PackageReference Include="Websocket.Client" Version="5.0" />
    <!-- Voice dependencies -->
    <PackageReference Include="Concentus" Version="2.1.2" />
    <PackageReference Include="Sodium.Core" Version="1.3.6" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>


</Project>
