<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0;netstandard2.1</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>annotations</Nullable>
    <DebugSymbols>true</DebugSymbols>
    <EmbedAllSources>true</EmbedAllSources>
    <DebugType>portable</DebugType>
	
	<!-- NuGet package info -->
    <PackageId>Fluxer.Net</PackageId>
    <Version>2.7.1</Version>
    <Authors>Nexfinity</Authors>
    <Company>Nexfinity</Company>
    <Description>A .NET library for Fluxer bot development.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://fluxer.net</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Nexfinity/Fluxer.Net</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

    <!-- Optional but good practice -->
    <PackageTags>fluxer;bot;library;dotnet</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageReadmeFile>README.md</PackageReadmeFile>
	<LangVersion>latest</LangVersion>
	<GenerateDocumentationFile>True</GenerateDocumentationFile>
	<DocumentationFile>FluxerNet.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="2.3.11" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="serilog" Version="4.4.0" />
    <PackageReference Include="serilog.sinks.console" Version="6.1.1" />
    <PackageReference Include="System.Collections.Immutable" Version="10.0.10" />
    <PackageReference Include="Websocket.Client" Version="5.5.0" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
  </ItemGroup>

	<ItemGroup Condition="$(TargetFramework) != 'netstandard2.1'">
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup Condition="$(TargetFramework) == 'netstandard2.1'">
		<PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
	</ItemGroup>
</Project>
    