name: 💡 Feature
description: Request a feature
title: "[Feature]: "
labels: ["enhancement"]
type: "Feature"
body:
  - type: markdown
    attributes:
      value: Suggest a new feature or improvement!
  - type: checkboxes
    attributes:
      label: Check The Docs
      description: Please check the [Fluxer.net Docs](https://fluxer.net/api/index.html) for guides, examples and reference before making a request.
      options:
      - label: "I have checked the docs"
        required: true
  - type: textarea
    id: description
    attributes: 
      label: Description
      description: A brief explanation of your request.
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Example
      description: Include an example of your feature/request.
      placeholder: |
        ```cs
        FluxerClient _client = new FluxerClient();
        ```
    validations:
      required: false   
