namespace Squll.Net.Objects.DataTables;

[Flags]
public enum Permissions
{
	None = 0,
	Administrator = 1 << 0,
	ChangeDisplayName = 1 << 1,
	CreateInvites = 1 << 2,
	ViewAnalytics = 1 << 3,
	ViewChannel = 1 << 4,
	ViewChannelHistory = 1 << 5,
	SendMessages = 1 << 6,
	SendMessagesInThreads = 1 << 7,
	AddReactionsExisting = 1 << 8,
	AddReactionsNew = 1 << 9,
	AttachFiles = 1 << 10,
	EmbedLinks = 1 << 11,
	MentionEveryone = 1 << 12,
	UseApplicationCommands = 1 << 13,
	UseExpressions = 1 << 14,
	UseExpressionsExternal = 1 << 15,
	UseExtendedMarkdown = 1 << 16,
	CreatePublicThreads = 1 << 17,
	CreatePrivateThreads = 1 << 18,
	ManageApplications = 1 << 19,
	ManageAutomod = 1 << 20,
	ManageBans = 1 << 21,
	ManageCalendar = 1 << 22,
	ManageExpressions = 1 << 23,
	ManageInvites = 1 << 24,
	ManageMembers = 1 << 25,
	ManageModmail = 1 << 26,
	ManagePins = 1 << 27,
	ManageRoles = 1 << 28,
	ManageSnippets = 1 << 29,
	ManageChannels = 1 << 30,
	ManageSquad = 1 << 31,
	ManageThreadTags = 1,
	ManageThreads = 2,
	ManageTimeouts = 4,
	ManageWarnings = 8,
	ManageWebhooks = 16,
	ManageMessages = 32,
	ManageReactions = 64
}
