### YamlMime:ManagedReference
items:
- uid: Fluxer.Net.ApplicationJson
  commentId: T:Fluxer.Net.ApplicationJson
  id: ApplicationJson
  parent: Fluxer.Net
  children:
  - Fluxer.Net.ApplicationJson.Bot
  - Fluxer.Net.ApplicationJson.RedirectUrls
  langs:
  - csharp
  - vb
  name: ApplicationJson
  nameWithType: ApplicationJson
  fullName: Fluxer.Net.ApplicationJson
  type: Class
  source:
    remote:
      path: Fluxer.Net/Data/Apps/ApplicationJson.cs
      branch: release
      repo: https://github.com/Nexfinity/Fluxer.Net
    id: ApplicationJson
    path: ../Fluxer.Net/Data/Apps/ApplicationJson.cs
    startLine: 5
  assemblies:
  - Fluxer.Net
  namespace: Fluxer.Net
  summary: Supports all classes in the .NET class hierarchy and provides low-level services to derived classes. This is the ultimate base class of all .NET classes; it is the root of the type hierarchy.
  example: []
  syntax:
    content: 'public class ApplicationJson : PartialApplicationJson, IPartialApplication, IApplication'
    content.vb: Public Class ApplicationJson Inherits PartialApplicationJson Implements IPartialApplication, IApplication
  inheritance:
  - System.Object
  - Fluxer.Net.PartialApplicationJson
  implements:
  - Fluxer.Net.IPartialApplication
  - Fluxer.Net.IApplication
  inheritedMembers:
  - Fluxer.Net.PartialApplicationJson.Id
  - Fluxer.Net.PartialApplicationJson.Name
  - Fluxer.Net.PartialApplicationJson.Icon
  - Fluxer.Net.PartialApplicationJson.Description
  - Fluxer.Net.PartialApplicationJson.IsPublic
  - Fluxer.Net.PartialApplicationJson.RequiresCodeGrant
  - Fluxer.Net.PartialApplicationJson.Flags
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Fluxer.Net.ApplicationJson.RedirectUrls
  commentId: P:Fluxer.Net.ApplicationJson.RedirectUrls
  id: RedirectUrls
  parent: Fluxer.Net.ApplicationJson
  langs:
  - csharp
  - vb
  name: RedirectUrls
  nameWithType: ApplicationJson.RedirectUrls
  fullName: Fluxer.Net.ApplicationJson.RedirectUrls
  type: Property
  source:
    remote:
      path: Fluxer.Net/Data/Apps/ApplicationJson.cs
      branch: release
      repo: https://github.com/Nexfinity/Fluxer.Net
    id: RedirectUrls
    path: ../Fluxer.Net/Data/Apps/ApplicationJson.cs
    startLine: 8
  assemblies:
  - Fluxer.Net
  namespace: Fluxer.Net
  summary: The registered redirect URIs for OAuth2.
  remarks: Maximum 20
  example: []
  syntax:
    content: >-
      [JsonProperty("redirect_urls")]

      public string[] RedirectUrls { get; set; }
    parameters: []
    return:
      type: System.String[]
    content.vb: >-
      <JsonProperty("redirect_urls")>

      Public Property RedirectUrls As String()
  overload: Fluxer.Net.ApplicationJson.RedirectUrls*
  implements:
  - Fluxer.Net.IApplication.RedirectUrls
  attributes:
  - type: Newtonsoft.Json.JsonPropertyAttribute
    ctor: Newtonsoft.Json.JsonPropertyAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: redirect_urls
- uid: Fluxer.Net.ApplicationJson.Bot
  commentId: P:Fluxer.Net.ApplicationJson.Bot
  id: Bot
  parent: Fluxer.Net.ApplicationJson
  langs:
  - csharp
  - vb
  name: Bot
  nameWithType: ApplicationJson.Bot
  fullName: Fluxer.Net.ApplicationJson.Bot
  type: Property
  source:
    remote:
      path: Fluxer.Net/Data/Apps/ApplicationJson.cs
      branch: release
      repo: https://github.com/Nexfinity/Fluxer.Net
    id: Bot
    path: ../Fluxer.Net/Data/Apps/ApplicationJson.cs
    startLine: 12
  assemblies:
  - Fluxer.Net
  namespace: Fluxer.Net
  example: []
  syntax:
    content: >-
      [JsonProperty("bot")]

      public UserJson Bot { get; set; }
    parameters: []
    return:
      type: Fluxer.Net.UserJson
    content.vb: >-
      <JsonProperty("bot")>

      Public Property Bot As UserJson
  overload: Fluxer.Net.ApplicationJson.Bot*
  attributes:
  - type: Newtonsoft.Json.JsonPropertyAttribute
    ctor: Newtonsoft.Json.JsonPropertyAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: bot
references:
- uid: Fluxer.Net
  commentId: N:Fluxer.Net
  href: Fluxer.html
  name: Fluxer.Net
  nameWithType: Fluxer.Net
  fullName: Fluxer.Net
  spec.csharp:
  - uid: Fluxer
    name: Fluxer
    href: Fluxer.html
  - name: .
  - uid: Fluxer.Net
    name: Net
    href: Fluxer.Net.html
  spec.vb:
  - uid: Fluxer
    name: Fluxer
    href: Fluxer.html
  - name: .
  - uid: Fluxer.Net
    name: Net
    href: Fluxer.Net.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Fluxer.Net.PartialApplicationJson
  commentId: T:Fluxer.Net.PartialApplicationJson
  parent: Fluxer.Net
  href: Fluxer.Net.PartialApplicationJson.html
  name: PartialApplicationJson
  nameWithType: PartialApplicationJson
  fullName: Fluxer.Net.PartialApplicationJson
- uid: Fluxer.Net.IPartialApplication
  commentId: T:Fluxer.Net.IPartialApplication
  parent: Fluxer.Net
  href: Fluxer.Net.IPartialApplication.html
  name: IPartialApplication
  nameWithType: IPartialApplication
  fullName: Fluxer.Net.IPartialApplication
- uid: Fluxer.Net.IApplication
  commentId: T:Fluxer.Net.IApplication
  parent: Fluxer.Net
  href: Fluxer.Net.IApplication.html
  name: IApplication
  nameWithType: IApplication
  fullName: Fluxer.Net.IApplication
- uid: Fluxer.Net.PartialApplicationJson.Id
  commentId: P:Fluxer.Net.PartialApplicationJson.Id
  parent: Fluxer.Net.PartialApplicationJson
  href: Fluxer.Net.PartialApplicationJson.html#Fluxer_Net_PartialApplicationJson_Id
  name: Id
  nameWithType: PartialApplicationJson.Id
  fullName: Fluxer.Net.PartialApplicationJson.Id
- uid: Fluxer.Net.PartialApplicationJson.Name
  commentId: P:Fluxer.Net.PartialApplicationJson.Name
  parent: Fluxer.Net.PartialApplicationJson
  href: Fluxer.Net.PartialApplicationJson.html#Fluxer_Net_PartialApplicationJson_Name
  name: Name
  nameWithType: PartialApplicationJson.Name
  fullName: Fluxer.Net.PartialApplicationJson.Name
- uid: Fluxer.Net.PartialApplicationJson.Icon
  commentId: P:Fluxer.Net.PartialApplicationJson.Icon
  parent: Fluxer.Net.PartialApplicationJson
  href: Fluxer.Net.PartialApplicationJson.html#Fluxer_Net_PartialApplicationJson_Icon
  name: Icon
  nameWithType: PartialApplicationJson.Icon
  fullName: Fluxer.Net.PartialApplicationJson.Icon
- uid: Fluxer.Net.PartialApplicationJson.Description
  commentId: P:Fluxer.Net.PartialApplicationJson.Description
  parent: Fluxer.Net.PartialApplicationJson
  href: Fluxer.Net.PartialApplicationJson.html#Fluxer_Net_PartialApplicationJson_Description
  name: Description
  nameWithType: PartialApplicationJson.Description
  fullName: Fluxer.Net.PartialApplicationJson.Description
- uid: Fluxer.Net.PartialApplicationJson.IsPublic
  commentId: P:Fluxer.Net.PartialApplicationJson.IsPublic
  parent: Fluxer.Net.PartialApplicationJson
  href: Fluxer.Net.PartialApplicationJson.html#Fluxer_Net_PartialApplicationJson_IsPublic
  name: IsPublic
  nameWithType: PartialApplicationJson.IsPublic
  fullName: Fluxer.Net.PartialApplicationJson.IsPublic
- uid: Fluxer.Net.PartialApplicationJson.RequiresCodeGrant
  commentId: P:Fluxer.Net.PartialApplicationJson.RequiresCodeGrant
  parent: Fluxer.Net.PartialApplicationJson
  href: Fluxer.Net.PartialApplicationJson.html#Fluxer_Net_PartialApplicationJson_RequiresCodeGrant
  name: RequiresCodeGrant
  nameWithType: PartialApplicationJson.RequiresCodeGrant
  fullName: Fluxer.Net.PartialApplicationJson.RequiresCodeGrant
- uid: Fluxer.Net.PartialApplicationJson.Flags
  commentId: P:Fluxer.Net.PartialApplicationJson.Flags
  parent: Fluxer.Net.PartialApplicationJson
  href: Fluxer.Net.PartialApplicationJson.html#Fluxer_Net_PartialApplicationJson_Flags
  name: Flags
  nameWithType: PartialApplicationJson.Flags
  fullName: Fluxer.Net.PartialApplicationJson.Flags
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Fluxer.Net.ApplicationJson.RedirectUrls*
  commentId: Overload:Fluxer.Net.ApplicationJson.RedirectUrls
  href: Fluxer.Net.ApplicationJson.html#Fluxer_Net_ApplicationJson_RedirectUrls
  name: RedirectUrls
  nameWithType: ApplicationJson.RedirectUrls
  fullName: Fluxer.Net.ApplicationJson.RedirectUrls
- uid: Fluxer.Net.IApplication.RedirectUrls
  commentId: P:Fluxer.Net.IApplication.RedirectUrls
  parent: Fluxer.Net.IApplication
  href: Fluxer.Net.IApplication.html#Fluxer_Net_IApplication_RedirectUrls
  name: RedirectUrls
  nameWithType: IApplication.RedirectUrls
  fullName: Fluxer.Net.IApplication.RedirectUrls
- uid: System.String[]
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string[]
  nameWithType: string[]
  fullName: string[]
  nameWithType.vb: String()
  fullName.vb: String()
  name.vb: String()
  spec.csharp:
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '['
  - name: ']'
  spec.vb:
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: (
  - name: )
- uid: Fluxer.Net.ApplicationJson.Bot*
  commentId: Overload:Fluxer.Net.ApplicationJson.Bot
  href: Fluxer.Net.ApplicationJson.html#Fluxer_Net_ApplicationJson_Bot
  name: Bot
  nameWithType: ApplicationJson.Bot
  fullName: Fluxer.Net.ApplicationJson.Bot
- uid: Fluxer.Net.UserJson
  commentId: T:Fluxer.Net.UserJson
  parent: Fluxer.Net
  href: Fluxer.Net.UserJson.html
  name: UserJson
  nameWithType: UserJson
  fullName: Fluxer.Net.UserJson
