### YamlMime:ManagedReference
items:
- uid: Fluxer.Net.IApplication
  commentId: T:Fluxer.Net.IApplication
  id: IApplication
  parent: Fluxer.Net
  children:
  - Fluxer.Net.IApplication.Bot
  - Fluxer.Net.IApplication.RedirectUrls
  langs:
  - csharp
  - vb
  name: IApplication
  nameWithType: IApplication
  fullName: Fluxer.Net.IApplication
  type: Interface
  source:
    remote:
      path: Fluxer.Net/Data/Apps/IApplication.cs
      branch: release
      repo: https://github.com/Nexfinity/Fluxer.Net
    id: IApplication
    path: ../Fluxer.Net/Data/Apps/IApplication.cs
    startLine: 5
  assemblies:
  - Fluxer.Net
  namespace: Fluxer.Net
  summary: Application/bot used to interact with the Fluxer platform and API.
  example: []
  syntax:
    content: public interface IApplication
    content.vb: Public Interface IApplication
  derivedClasses:
  - Fluxer.Net.Application
  - Fluxer.Net.ApplicationJson
- uid: Fluxer.Net.IApplication.RedirectUrls
  commentId: P:Fluxer.Net.IApplication.RedirectUrls
  id: RedirectUrls
  parent: Fluxer.Net.IApplication
  langs:
  - csharp
  - vb
  name: RedirectUrls
  nameWithType: IApplication.RedirectUrls
  fullName: Fluxer.Net.IApplication.RedirectUrls
  type: Property
  source:
    remote:
      path: Fluxer.Net/Data/Apps/IApplication.cs
      branch: release
      repo: https://github.com/Nexfinity/Fluxer.Net
    id: RedirectUrls
    path: ../Fluxer.Net/Data/Apps/IApplication.cs
    startLine: 13
  assemblies:
  - Fluxer.Net
  namespace: Fluxer.Net
  summary: The registered redirect URIs for OAuth2.
  remarks: Maximum 20
  example: []
  syntax:
    content: string[] RedirectUrls { get; }
    parameters: []
    return:
      type: System.String[]
    content.vb: ReadOnly Property RedirectUrls As String()
  overload: Fluxer.Net.IApplication.RedirectUrls*
- uid: Fluxer.Net.IApplication.Bot
  commentId: P:Fluxer.Net.IApplication.Bot
  id: Bot
  parent: Fluxer.Net.IApplication
  langs:
  - csharp
  - vb
  name: Bot
  nameWithType: IApplication.Bot
  fullName: Fluxer.Net.IApplication.Bot
  type: Property
  source:
    remote:
      path: Fluxer.Net/Data/Apps/IApplication.cs
      branch: release
      repo: https://github.com/Nexfinity/Fluxer.Net
    id: Bot
    path: ../Fluxer.Net/Data/Apps/IApplication.cs
    startLine: 18
  assemblies:
  - Fluxer.Net
  namespace: Fluxer.Net
  summary: Detailed bot user metadata.
  example: []
  syntax:
    content: IUser Bot { get; }
    parameters: []
    return:
      type: Fluxer.Net.IUser
    content.vb: ReadOnly Property Bot As IUser
  overload: Fluxer.Net.IApplication.Bot*
references:
- uid: Fluxer.Net
  commentId: N:Fluxer.Net
  href: Fluxer.html
  name: Fluxer.Net
  nameWithType: Fluxer.Net
  fullName: Fluxer.Net
  spec.csharp:
  - uid: Fluxer
    name: Fluxer
    href: Fluxer.html
  - name: .
  - uid: Fluxer.Net
    name: Net
    href: Fluxer.Net.html
  spec.vb:
  - uid: Fluxer
    name: Fluxer
    href: Fluxer.html
  - name: .
  - uid: Fluxer.Net
    name: Net
    href: Fluxer.Net.html
- uid: Fluxer.Net.IApplication.RedirectUrls*
  commentId: Overload:Fluxer.Net.IApplication.RedirectUrls
  href: Fluxer.Net.IApplication.html#Fluxer_Net_IApplication_RedirectUrls
  name: RedirectUrls
  nameWithType: IApplication.RedirectUrls
  fullName: Fluxer.Net.IApplication.RedirectUrls
- uid: System.String[]
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string[]
  nameWithType: string[]
  fullName: string[]
  nameWithType.vb: String()
  fullName.vb: String()
  name.vb: String()
  spec.csharp:
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '['
  - name: ']'
  spec.vb:
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: (
  - name: )
- uid: Fluxer.Net.IApplication.Bot*
  commentId: Overload:Fluxer.Net.IApplication.Bot
  href: Fluxer.Net.IApplication.html#Fluxer_Net_IApplication_Bot
  name: Bot
  nameWithType: IApplication.Bot
  fullName: Fluxer.Net.IApplication.Bot
- uid: Fluxer.Net.IUser
  commentId: T:Fluxer.Net.IUser
  parent: Fluxer.Net
  href: Fluxer.Net.IUser.html
  name: IUser
  nameWithType: IUser
  fullName: Fluxer.Net.IUser
